name: Deploy to Reloaded NuGet
on:
    workflow_dispatch:
        inputs:
            mod:
                description: "Mod name to deploy"
                required: true
                type: string

jobs:
    deploy:
        name: Deploy to Reloaded NuGet
        runs-on: windows-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
              with:
                  submodules: true

            - name: Install .NET
              uses: actions/setup-dotnet@v3
              with:
                  dotnet-version: |
                      5.0.x
                      8.0.x

            - name: Build and upload
              run: powershell ./publish.ps1 ${{ inputs.mod }}
              env:
                  CI: true
                  NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}

            - name: Upload NuGet artifact
              uses: actions/upload-artifact@v4
              with:
                  name: ${{ inputs.mod }}
                  path: ./temp/nuget
